export default [
  {
    id: 1,
    image: `img/apartment-01.jpg`,
    isPremium: true,
    price: 120,
    name: `Beautiful &amp; luxurious apartment at great location`,
    type: `Apartment`,
    rating: 93,
  },
  {
    id: 2,
    image: `img/room.jpg`,
    isPremium: false,
    price: 80,
    name: `Wood and stone place`,
    type: `Private room`,
    rating: 80,
  },
  {
    id: 3,
    image: `img/apartment-02.jpg`,
    isPremium: false,
    price: 132,
    name: `Canal View Prinsengracht`,
    type: `Apartment`,
    rating: 80,
  },
  {
    id: 4,
    image: `img/apartment-03.jpg`,
    isPremium: true,
    price: 180,
    name: `Nice, cozy, warm big bed apartment`,
    type: `Apartment`,
    rating: 100,
  },
];
